<div class="foot">
    <div id="foot-superior">
        <div class="content-inner">
            <p>
                <i class="fas fa-map-marker-alt"></i>
                ENDEREÇO: <br>
                Cristolândia Masculina em Porto Seguro. <br>
                Rua das Jaboticabas, 374. <br>
                Sapoti - Porto Seguro - BA. <br>
                CEP: 45810-000. <br>
                <br>
                <i class="fas fa-envelope"></i>
                E-MAIL: <br>
                cristolandiaportoseguro@gmail.com <br>
                <br>
            </p>
        </div>
        <div class="content-inner">
            <a href="https://www.convencaobatista.com.br">
                <img src="../assets/img/logoCBB.png" alt=""></img>
            </a>
            <a href="https://www.cristolandia.org">
                <img src="../assets/img/logoCristolandia.png" alt=""></img>
            </a>
            <a href="https://www.missoesnacionais.org">
                <img src="../assets/img/logoJMN.png" alt=""></img>
            </a>
            <a href="https://www.radicalbrasil.org">
                <img src="../assets/img/logoRadical.png" alt=""></img>
            </a>
        </div>
        <div class="content-inner">
          <p>
            <i class="fas fa-phone"></i>
            TELEFONE: <br>
            (073) 9 9112-9060 - Gestão local<br>
            (071) 9 9227-5588 - Coordenação estadual<br>
            <br>
            <br>
            Visite-nos:<br>
            <a href="https://www.facebook.com/CristolandiaBahia"><i class="socialmedia fab fa-facebook-square"></i></a>
            <a href="https://www.instagram.com/CristolandiaPortoSeguro"><i class="socialmedia fab fa-instagram"></i></a>
            <a href="https://www.youtube.com/missoesnacionais"><i class="socialmedia fab fa-youtube"></i></a>
          </p>
        </div>
    </div>
    <!-- <div id="foot-inferior">

    </div> -->
</div>
<div class="copyright">
    <p>© 2018 | Cristolândia Bahia | Multiplicando discípulos de Cristo. </p>
</div>
