<nav id="navigation">
	<a href="index.php">
			<div class="logo">
					<img src="../assets/img/logocorretobranco.png">
			</div>
	</a>
	<label for="toggle">&#9776;</label>
	<input type="checkbox" id="toggle">
    <ul>
        <a href="index.php" class="scrollSuave"><li>Início</li></a>
        <a href="#about" class="scrollSuave"><li>Sobre nós</li></a>
        <a href="#team" class="scrollSuave"><li>Equipe</li></a>
        <!-- <a href="#contact-us" class="scrollSuave"><li>Contate-nos</li></a> -->
    </ul>
		<a href="helpus.php">
				<button type="button" name="cta" id="help-us">
						Faça Parte!
				</button>
		</a>
</nav>
