<nav id="navigation">
	<a href="#home">
		<img src="../assets/img/logombc.png">
	</a>
	<label for="toggle">&#9776;</label>
	<input type="checkbox" id="toggle">
    <ul>
        <a href="#home"><li>Início</li></a>
        <a href="#about"><li>Sobre</li></a>
        <a href="#speakers"><li>Parceiros</li></a>
        <a href="#schedule"><li>Contate-nos</li></a>
    </ul>
		<button type="button" name="cta" id="help-us">
				Faça Parte!
		</button>
</nav>
